### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dev-dsp** [jenkinsci/custom-war-packager#101]
Hello,
Is there any documentation or reference for CWP configuration file? 
Currently, I've copy-pasted samples from projects mentioned in README and for now it is ok, since my goal is covered by most of them.
In order to have full list of available parameters, however, I have to explore code.

Is it possible at least to publish something like that: https://github.com/jenkinsci/custom-war-packager#configuration-file, but with all possible keys (where applicable)?

Thanks in advance.

**Comment by dev-dsp** [comment]
For now I am mostly interested in full configurations for building Docker image, WAR and JfR image, so that it would be clear, what may and what may not be configured.
Do I understand it correctly that produced artifact type is only configured in buildSettings directive?

**Comment by oleg-nenashev** [comment]
> Do I understand it correctly that produced artifact type is only configured in buildSettings directive?

WAR is always produced. Docker and JFR images are produced depending on `buildSettings`, but they cannot be produced together from the same configuration. One minor build flow issue which could be fixed quickly.

> For now I am mostly interested in full configurations for building Docker image, WAR and JfR image, so that it would be clear, what may and what may not be configured.

I think it would be great to have a YAML spec for it.
I wanted to do so, but I have never got to it

**Comment by dev-dsp** [comment]
@oleg-nenashev thanks for clarification. 
Could you please suggest whether it is possible to use some minimal CWP configuration for taking WAR placed on remote and packing it into docker? Does this make any sense, or it is safe to reconstruct Dockerfile contents from JenkinsDockerfileBuilder.java?

I found that `source` attribute may contain `dir` child. For CASC, we use it for defining target yaml file, but seems that for building WAR itself, `dir` should point to exploded-war directory, is it correct?

As I understand, generated docker image consists of FROM, two LABELs and COPY. 
Is there any possibility that this schema may be changed later?

**Comment by dev-dsp** [comment]
huh

**Comment by oleg-nenashev** [comment]
@dev-dsp  If you expected a quick response, then it is not how the community always work. This request was in the todo list, but I have not got to it
