### ISSUE TITLE
Nexus Proxy url

### ISSUE THREAD

**Issue by srisaravananwt** [jenkinsci/custom-war-packager#128]
I need to use our own Nexus proxy url instead of update center url. Currently I am getting below error. How to resolve?

Downloading: http://repo.maven.apache.org/maven2/org/jenkins-ci/tools/maven-hpi-plugin/2.2/maven-hpi-plugin-2.2.pom
Plugin org.jenkins-ci.tools:maven-hpi-plugin:2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jenkins-ci.tools:maven-hpi-plugin:jar:2.2: Could not transfer artifact org.jenkins-ci.tools:maven-hpi-plugin:pom:2.2 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): repo.jenkins-ci.org: Name or service not known: Unknown host repo.jenkins-ci.org: Name or service not known -> [Help 1]
[21:34:27][Step 1/1] [ERROR]

**Comment by oleg-nenashev** [comment]
It can be specified by a Maven setting file which can be passed as an argument.
You can specify multiple update sites there.

But yes, you need to connect to Jenkins Maven Repo or its mirror if you want to run Custom WAR Packager. We do not mirror all our artifacts to Maven Central

**Comment by oleg-nenashev** [comment]
Closing since there is no follow-up from the requester
