### ISSUE TITLE
Can't use the CLI on Windows

### ISSUE THREAD

**Issue by kunerd** [jenkinsci/custom-war-packager#49]
It seems, that on Windows the parent environment is not forwarded to the spawned `mvn` process, like it is on Linux.
So that I get the following error, when I try to build a simple custom war configuration:
```
Exception in thread "main" java.io.IOException: Cannot run program "mvn" (in directory "tmp\prebuild"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessBuilder.start(Unknown Source)
	at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.runFor(SystemCommandHelper.java:29)
	at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.processFor(SystemCommandHelper.java:20)
	at io.jenkins.tools.warpackager.lib.util.MavenHelper.run(MavenHelper.java:60)
	at io.jenkins.tools.warpackager.lib.util.MavenHelper.run(MavenHelper.java:42)
	at io.jenkins.tools.warpackager.lib.impl.Builder.build(Builder.java:142)
	at io.jenkins.tools.warpackager.cli.Main.main(Main.java:56)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```
On Linux it works out of the box.

I can workaround this on windows, by calling the inner `mvn` command by myself:
```
cd tmp\prebuild
mvn package
```

**Comment by oleg-nenashev** [comment]
@kunerd Just to make sure. Is maven installed on your Windows machine and added to the default PATH?

**Comment by kunerd** [comment]
Yes, as I wrote in the second part, I can call it by myself from command line and it builds a working WAR file.

**Comment by oleg-nenashev** [comment]
Works on my machine. I should probably add an option for passing a path to Maven Home or binary.

**Comment by kunerd** [comment]
Thank you for your feedback, I think I need to take another look at my configuration.

**Comment by oleg-nenashev** [comment]
Also, it is possible to perform the build in Docker now: https://github.com/jenkins-x/jenkins-x-serverless/blob/master/Makefile#L25-L32. It might help with Windows

**Comment by kunerd** [comment]
I created a minimal working example to tackle down the problem. I called `ProcessBuilder` with different input parameters and for some reason it works on my machine, if I use one of the following to call `mvn` from within a Java app.
```
ArrayList<String> callArgs = new ArrayList<>();
// Either this:
// callArgs.add("cmd");
// callArgs.add("/c");
// or this works for me
callArgs.add("mvn.cmd");
callArgs.add("package");
// ...
 ProcessBuilder bldr = new ProcessBuilder(callArgs).inheritIO();
// ...
```
I use the following Versions of
* Windows: Win 7 x64 Professional
* Maven: 3.5.4
* Java: JDK 1.8.0_181

**Comment by FriedlTheFox** [comment]
I have the same issue under Win10.

**Comment by oleg-nenashev** [comment]
> @oleg-nenashev: Weird that it works on your machine, which windows version are you using?

It's Windows 10, but I have a history of custom tweaks for system environment tweaks on my machine to make it working in Unix way. I do not use Windows often, and my knowledge about this hacks is rusty. But I doubt that my machine can be considered as a reference Windows installation 

Anyway, the bottomline here is that we should actually fix it in CWP. It should be a trivial patch in https://github.com/jenkinsci/custom-war-packager/blob/master/custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java, all Maven CLI invocations in the code should be using this utility class. Answer to https://stackoverflow.com/questions/7966194/running-mvn-using-processbuilder referenced by @kunerd

**Comment by oleg-nenashev** [comment]
It was released in Custom WAR Packager 1.4

**Comment by oleg-nenashev** [comment]
@kunerd would you be able to double-check the release?
I also landed https://github.com/jenkinsci/custom-war-packager/pull/50. The PRs should work together, but I am not 100% sure

**Comment by andham** [comment]
Thanks, now it works for me on WIndows 10!

**Comment by kunerd** [comment]
The newest Maven plugin and the CLI are working for me.

**Comment by oleg-nenashev** [comment]
Thanks for the feedback!

**Comment by FriedlTheFox** [comment]
Thank you very much. Now on my Windows 10 it works fine, too.
