### ISSUE TITLE
Use local WAR file as war source

### ISSUE THREAD

**Issue by juaningan** [jenkinsci/custom-war-packager#89]
Hi Im trying to customize a Cloudbees Managed Master, but the only public source of package is the jenkins.war in official docker image.

So, can I use that local war file as war source?

**Comment by varyvol** [comment]
@juaningan Hi! This is an open source project and not a CloudBees one. You should talk to CloudBees support or partners program to get this answered.

**Comment by juaningan** [comment]
Ok I understand, but is not using a custom war (cloudbees or whatever) as war source a legitimate use of the packager?
